<?php
$env_items = array();
$dirfile_items = array(
		array('type' => 'dir', 'path' => 'data/cache'),
		array('type' => 'dir', 'path' => 'data/cache/adv'),
		array('type' => 'dir', 'path' => 'data/cache/rec_position'),
		array('type' => 'dir', 'path' => 'data/config'),
		array('type' => 'dir', 'path' => 'data/log'),
		array('type' => 'dir', 'path' => 'data/session'),
		array('type' => 'dir', 'path' => 'data/resource/phpqrcode/temp'),
		array('type' => 'dir', 'path' => 'data/upload'),
		array('type' => 'dir', 'path' => 'data/upload/mall/activity'),
		array('type' => 'dir', 'path' => 'data/upload/mall/adv'),
		array('type' => 'dir', 'path' => 'data/upload/mall/article'),
		array('type' => 'dir', 'path' => 'data/upload/mall/avatar'),
		array('type' => 'dir', 'path' => 'data/upload/mall/brand'),
		array('type' => 'dir', 'path' => 'data/upload/mall/common'),
		array('type' => 'dir', 'path' => 'data/upload/mall/complain'),
		array('type' => 'dir', 'path' => 'data/upload/mall/editor'),
		array('type' => 'dir', 'path' => 'data/upload/mall/goods_class'),
		array('type' => 'dir', 'path' => 'data/upload/mall/groupbuy'),
		array('type' => 'dir', 'path' => 'data/upload/mall/inform'),
		array('type' => 'dir', 'path' => 'data/upload/mall/login'),
		array('type' => 'dir', 'path' => 'data/upload/mall/member'),
		array('type' => 'dir', 'path' => 'data/upload/mall/membertag'),
		array('type' => 'dir', 'path' => 'data/upload/mall/pointprod'),
		array('type' => 'dir', 'path' => 'data/upload/mall/rec_position'),
		array('type' => 'dir', 'path' => 'data/upload/mall/refund'),
		array('type' => 'dir', 'path' => 'data/upload/mall/store'),
		array('type' => 'dir', 'path' => 'data/upload/mall/voucher'),
		array('type' => 'dir', 'path' => 'data/upload/mall/watermark'),
		array('type' => 'dir', 'path' => 'data/upload/circle'),
		array('type' => 'dir', 'path' => 'data/upload/reads'),
		array('type' => 'dir', 'path' => 'data/upload/shareshow'),
		array('type' => 'dir', 'path' => 'data/upload/delivery'),
		array('type' => 'dir', 'path' => 'data/upload/chain'),
		array('type' => 'dir', 'path' => 'data/upload/mobile'),
		array('type' => 'dir', 'path' => 'data/upload/mobile/ad'),
		array('type' => 'dir', 'path' => 'data/upload/mobile/category'),
		array('type' => 'dir', 'path' => 'data/upload/mobile/home'),
		array('type' => 'dir', 'path' => 'data/upload/mobile/special'),
		array('type' => 'dir', 'path' => 'data/upload/admin/avatar'),
		array('type' => 'dir', 'path' => 'mall/install'),
);

$func_items = array(
		array('name' => 'mysql_connect'),
		array('name' => 'fsockopen'),
		array('name' => 'gethostbyname'),
		array('name' => 'file_get_contents'),
		array('name' => 'mb_convert_encoding'),
		array('name' => 'json_encode'),
		array('name' => 'curl_init'),
);